'use client';

import React, { useEffect, useRef, useState } from 'react';

// MOSS相关的真实代码片段
const mossCodeSnippets = [
  'class MossLLM {',
  '  constructor(config) {',
  '    this.modelPath = config.modelPath;',
  '    this.tokenizer = new Tokenizer(config.tokenizerPath);',
  '    this.encoder = new Encoder();',
  '    this.decoder = new Decoder();',
  '    this.attention = new MultiHeadAttention(config.numHeads);',
  '    this.feedForward = new FeedForward(config.hiddenSize);',
  '    this.layerNorm1 = new LayerNorm(config.hiddenSize);',
  '    this.layerNorm2 = new LayerNorm(config.hiddenSize);',
  '    this.dropout = new Dropout(config.dropoutRate);',
  '  }',
  '',
  '  async generate(prompt, options = {}) {',
  '    const tokens = this.tokenizer.encode(prompt);',
  '    const maxTokens = options.maxTokens || 100;',
  '    const temperature = options.temperature || 0.7;',
  '    const topP = options.topP || 0.9;',
  '    const topK = options.topK || 50;',
  '',
  '    for (let i = 0; i < maxTokens; i++) {',
  '      const logits = await this.forward(tokens);',
  '      const nextToken = this.sample(logits, temperature, topP, topK);',
  '      tokens.push(nextToken);',
  '',
  '      if (nextToken === this.tokenizer.eosToken) {',
  '        break;',
  '      }',
  '    }',
  '',
  '    return this.tokenizer.decode(tokens);',
  '  }',
  '',
  '  async forward(tokens) {',
  '    // 模型前向传播',
  '    const embeddings = this.encoder.encode(tokens);',
  '    const positionalEmbeddings = this.getPositionalEmbeddings(tokens.length);',
  '    let hiddenStates = embeddings.add(positionalEmbeddings);',
  '    hiddenStates = this.dropout.apply(hiddenStates);',
  '',
  '    for (let layer of this.layers) {',
  '      hiddenStates = await layer.forward(hiddenStates);',
  '    }',
  '',
  '    return this.decoder.forward(hiddenStates);',
  '  }',
  '',
  '  getPositionalEmbeddings(length) {',
  '    const embeddings = [];',
  '    for (let pos = 0; pos < length; pos++) {',
  '      const pe = [];',
  '      for (let i = 0; i < this.hiddenSize; i += 2) {',
  '        pe[i] = Math.sin(pos / Math.pow(10000, i / this.hiddenSize));',
  '        pe[i + 1] = Math.cos(pos / Math.pow(10000, (i + 1) / this.hiddenSize));',
  '      }',
  '      embeddings.push(pe);',
  '    }',
  '    return embeddings;',
  '  }',
  '',
  '  sample(logits, temperature, topP, topK) {',
  '    // 采样下一个token',
  '    if (temperature === 0) {',
  '      return logits.argmax();',
  '    }',
  '',
  '    let scaledLogits = logits.map(l => l / temperature);',
  '    scaledLogits = this.applyTopK(scaledLogits, topK);',
  '    scaledLogits = this.applyTopP(scaledLogits, topP);',
  '    const probabilities = this.softmax(scaledLogits);',
  '    return this.multinomial(probabilities);',
  '  }',
  '',
  '  applyTopK(logits, k) {',
  '    const sortedIndices = logits',
  '      .map((val, idx) => [val, idx])',
  '      .sort((a, b) => b[0] - a[0])',
  '      .slice(0, k)',
  '      .map(([_, idx]) => idx);',
  '',
  '    return logits.map((val, idx) => sortedIndices.includes(idx) ? val : -Infinity);',
  '  }',
  '',
  '  applyTopP(logits, p) {',
  '    const sortedLogits = [...logits].sort((a, b) => b - a);',
  '    const cumulativeProbs = this.softmax(sortedLogits).reduce((acc, prob, i) => {',
  '      acc.push((acc[i - 1] || 0) + prob);',
  '      return acc;',
  '    }, []);',
  '',
  '    const cutoffIndex = cumulativeProbs.findIndex(cp => cp >= p);',
  '    const cutoffValue = sortedLogits[cutoffIndex];',
  '',
  '    return logits.map(val => val >= cutoffValue ? val : -Infinity);',
  '  }',
  '',
  '  softmax(logits) {',
  '    const maxLogit = Math.max(...logits);',
  '    const expLogits = logits.map(l => Math.exp(l - maxLogit));',
  '    const sumExp = expLogits.reduce((a, b) => a + b, 0);',
  '    return expLogits.map(e => e / sumExp);',
  '  }',
  '',
  '  multinomial(probabilities) {',
  '    const rand = Math.random();',
  '    let cumulative = 0;',
  '    for (let i = 0; i < probabilities.length; i++) {',
  '      cumulative += probabilities[i];',
  '      if (rand <= cumulative) {',
  '        return i;',
  '      }',
  '    }',
  '    return probabilities.length - 1;',
  '  }',
  '}',
  '',
  'class TransformerLayer {',
  '  constructor(config) {',
  '    this.selfAttention = new MultiHeadAttention(config.numHeads, config.hiddenSize);',
  '    this.crossAttention = config.useCrossAttention ? new MultiHeadAttention(config.numHeads, config.hiddenSize) : null;',
  '    this.feedForward = new FeedForward(config.hiddenSize, config.intermediateSize);',
  '    this.layerNorm1 = new LayerNorm(config.hiddenSize);',
  '    this.layerNorm2 = new LayerNorm(config.hiddenSize);',
  '    this.layerNorm3 = config.useCrossAttention ? new LayerNorm(config.hiddenSize) : null;',
  '    this.dropout1 = new Dropout(config.dropoutRate);',
  '    this.dropout2 = new Dropout(config.dropoutRate);',
  '    this.dropout3 = config.useCrossAttention ? new Dropout(config.dropoutRate) : null;',
  '  }',
  '',
  '  async forward(hiddenStates, encoderOutputs = null, attentionMask = null) {',
  '    // Self-attention sublayer',
  '    const normedStates1 = this.layerNorm1.forward(hiddenStates);',
  '    const attentionOutput = await this.selfAttention.forward(',
  '      normedStates1, normedStates1, normedStates1, attentionMask',
  '    );',
  '    hiddenStates = hiddenStates.add(this.dropout1.apply(attentionOutput));',
  '',
  '    // Cross-attention sublayer (if enabled)',
  '    if (this.crossAttention && encoderOutputs) {',
  '      const normedStates2 = this.layerNorm3.forward(hiddenStates);',
  '      const crossAttentionOutput = await this.crossAttention.forward(',
  '        normedStates2, encoderOutputs, encoderOutputs, attentionMask',
  '      );',
  '      hiddenStates = hiddenStates.add(this.dropout3.apply(crossAttentionOutput));',
  '    }',
  '',
  '    // Feed-forward sublayer',
  '    const normedStates3 = this.layerNorm2.forward(hiddenStates);',
  '    const ffOutput = this.feedForward.forward(normedStates3);',
  '    hiddenStates = hiddenStates.add(this.dropout2.apply(ffOutput));',
  '',
  '    return hiddenStates;',
  '  }',
  '}',
  '',
  'class MultiHeadAttention {',
  '  constructor(numHeads, hiddenSize) {',
  '    this.numHeads = numHeads;',
  '    this.hiddenSize = hiddenSize;',
  '    this.headSize = hiddenSize / numHeads;',
  '    this.wq = new LinearLayer(hiddenSize, hiddenSize);',
  '    this.wk = new LinearLayer(hiddenSize, hiddenSize);',
  '    this.wv = new LinearLayer(hiddenSize, hiddenSize);',
  '    this.wo = new LinearLayer(hiddenSize, hiddenSize);',
  '  }',
  '',
  '  async forward(q, k, v, mask = null) {',
  '    const batchSize = q.length;',
  '    const seqLength = q[0].length;',
  '',
  '    // Linear projections',
  '    const qProj = this.wq.forward(q);',
  '    const kProj = this.wk.forward(k);',
  '    const vProj = this.wv.forward(v);',
  '',
  '    // Split into heads',
  '    const qHeads = this.splitHeads(qProj, batchSize, seqLength);',
  '    const kHeads = this.splitHeads(kProj, batchSize, seqLength);',
  '    const vHeads = this.splitHeads(vProj, batchSize, seqLength);',
  '',
  '    // Scaled dot-product attention',
  '    const attentionScores = this.scaledDotProductAttention(qHeads, kHeads, mask);',
  '    const attentionOutput = this.matmul(attentionScores, vHeads);',
  '',
  '    // Concatenate heads',
  '    const concatenated = this.concatenateHeads(attentionOutput, batchSize, seqLength);',
  '',
  '    // Final linear projection',
  '    return this.wo.forward(concatenated);',
  '  }',
  '',
  '  splitHeads(x, batchSize, seqLength) {',
  '    const reshaped = [];',
  '    for (let b = 0; b < batchSize; b++) {',
  '      const batchHeads = [];',
  '      for (let h = 0; h < this.numHeads; h++) {',
  '        const head = [];',
  '        for (let s = 0; s < seqLength; s++) {',
  '          const start = h * this.headSize;',
  '          const end = start + this.headSize;',
  '          head.push(x[b][s].slice(start, end));',
  '        }',
  '        batchHeads.push(head);',
  '      }',
  '      reshaped.push(batchHeads);',
  '    }',
  '    return reshaped;',
  '  }',
  '',
  '  scaledDotProductAttention(q, k, mask) {',
  '    const dk = this.headSize;',
  '    let scores = this.matmul(q, this.transpose(k, -2, -1));',
  '    scores = scores.map(row => row.map(val => val / Math.sqrt(dk)));',
  '',
  '    if (mask) {',
  '      scores = scores.map((row, i) => row.map((val, j) => mask[i][j] ? val : -Infinity));',
  '    }',
  '',
  '    return scores.map(row => this.softmax(row));',
  '  }',
  '',
  '  transpose(x, dim1, dim2) {',
  '    const transposed = [];',
  '    for (let i = 0; i < x[0].length; i++) {',
  '      const newRow = [];',
  '      for (let j = 0; j < x.length; j++) {',
  '        newRow.push(x[j][i]);',
  '      }',
  '      transposed.push(newRow);',
  '    }',
  '    return transposed;',
  '  }',
  '',
  '  matmul(a, b) {',
  '    const result = [];',
  '    for (let i = 0; i < a.length; i++) {',
  '      const row = [];',
  '      for (let j = 0; j < b[0].length; j++) {',
  '        let sum = 0;',
  '        for (let k = 0; k < a[0].length; k++) {',
  '          sum += a[i][k] * b[k][j];',
  '        }',
  '        row.push(sum);',
  '      }',
  '      result.push(row);',
  '    }',
  '    return result;',
  '  }',
  '',
  '  concatenateHeads(x, batchSize, seqLength) {',
  '    const concatenated = [];',
  '    for (let b = 0; b < batchSize; b++) {',
  '      const batch = [];',
  '      for (let s = 0; s < seqLength; s++) {',
  '        const token = [];',
  '        for (let h = 0; h < this.numHeads; h++) {',
  '          token.push(...x[b][h][s]);',
  '        }',
  '        batch.push(token);',
  '      }',
  '      concatenated.push(batch);',
  '    }',
  '    return concatenated;',
  '  }',
  '}',
  '',
  'class FeedForward {',
  '  constructor(hiddenSize, intermediateSize) {',
  '    this.linear1 = new LinearLayer(hiddenSize, intermediateSize);',
  '    this.linear2 = new LinearLayer(intermediateSize, hiddenSize);',
  '    this.activation = new GELU();',
  '  }',
  '',
  '  forward(x) {',
  '    return this.linear2.forward(this.activation.forward(this.linear1.forward(x)));',
  '  }',
  '}',
  '',
  'class GELU {',
  '  forward(x) {',
  '    const cdf = 0.5 * (1.0 + Math.tanh(Math.sqrt(2 / Math.PI) * (x + 0.044715 * Math.pow(x, 3))));',
  '    return x * cdf;',
  '  }',
  '}',
  '',
  'class LinearLayer {',
  '  constructor(inputSize, outputSize) {',
  '    this.weights = this.initializeWeights(inputSize, outputSize);',
  '    this.bias = new Array(outputSize).fill(0);',
  '  }',
  '',
  '  initializeWeights(inputSize, outputSize) {',
  '    const weights = [];',
  '    const scale = Math.sqrt(2 / (inputSize + outputSize));',
  '    for (let i = 0; i < inputSize; i++) {',
  '      const row = [];',
  '      for (let j = 0; j < outputSize; j++) {',
  '        row.push((Math.random() - 0.5) * 2 * scale);',
  '      }',
  '      weights.push(row);',
  '    }',
  '    return weights;',
  '  }',
  '',
  '  forward(x) {',
  '    const result = [];',
  '    for (let i = 0; i < x.length; i++) {',
  '      const row = [];',
  '      for (let j = 0; j < this.weights[0].length; j++) {',
  '        let sum = this.bias[j];',
  '        for (let k = 0; k < x[i].length; k++) {',
  '          sum += x[i][k] * this.weights[k][j];',
  '        }',
  '        row.push(sum);',
  '      }',
  '      result.push(row);',
  '    }',
  '    return result;',
  '  }',
  '}',
  '',
  'class LayerNorm {',
  '  constructor(hiddenSize, epsilon = 1e-5) {',
  '    this.gamma = new Array(hiddenSize).fill(1);',
  '    this.beta = new Array(hiddenSize).fill(0);',
  '    this.epsilon = epsilon;',
  '  }',
  '',
  '  forward(x) {',
  '    const mean = x.reduce((a, b) => a + b, 0) / x.length;',
  '    const variance = x.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / x.length;',
  '    return x.map((val, i) => this.gamma[i] * (val - mean) / Math.sqrt(variance + this.epsilon) + this.beta[i]);',
  '  }',
  '}',
  '',
  'class Dropout {',
  '  constructor(dropoutRate) {',
  '    this.dropoutRate = dropoutRate;',
  '  }',
  '',
  '  apply(x, training = true) {',
  '    if (!training) return x;',
  '    const mask = x.map(() => Math.random() > this.dropoutRate ? 1 : 0);',
  '    return x.map((val, i) => val * mask[i] / (1 - this.dropoutRate));',
  '  }',
  '}',
  '',
  'class Tokenizer {',
  '  constructor(vocabPath) {',
  '    this.vocab = this.loadVocab(vocabPath);',
  '    this.vocabReverse = this.buildReverseVocab();',
  '    this.eosToken = this.vocab["<|endoftext|>"];',
  '    this.bosToken = this.vocab["<|beginoftext|>"];',
  '    this.unkToken = this.vocab["<|unk|>"];',
  '    this.padToken = this.vocab["<|pad|>"];',
  '  }',
  '',
  '  loadVocab(vocabPath) {',
  '    // 在实际实现中从文件加载',
  '    const vocab = {};',
  '    const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?/\\\\~` \'\"";',
  '    let index = 0;',
  '',
  '    for (const char of chars) {',
  '      vocab[char] = index++;',
  '    }',
  '',
  '    vocab["<|endoftext|>"] = index++;',
  '    vocab["<|beginoftext|>"] = index++;',
  '    vocab["<|unk|>"] = index++;',
  '    vocab["<|pad|>"] = index++;',
  '',
  '    return vocab;',
  '  }',
  '',
  '  buildReverseVocab() {',
  '    const reverse = {};',
  '    for (const [key, value] of Object.entries(this.vocab)) {',
  '      reverse[value] = key;',
  '    }',
  '    return reverse;',
  '  }',
  '',
  '  encode(text) {',
  '    // 文本编码为tokens',
  '    const tokens = [this.bosToken];',
  '    for (const char of text) {',
  '      tokens.push(this.vocab[char] || this.unkToken);',
  '    }',
  '    tokens.push(this.eosToken);',
  '    return tokens;',
  '  }',
  '',
  '  decode(tokens) {',
  '    // tokens解码为文本',
  '    return tokens',
  '      .filter(token => token !== this.bosToken && token !== this.eosToken && token !== this.padToken)',
  '      .map(token => this.vocabReverse[token] || "<|unk|>")',
  '      .join("");',
  '  }',
  '',
  '  tokenize(text) {',
  '    // 更高级的tokenization',
  '    const words = text.split(/\\s+/);',
  '    const tokens = [];',
  '',
  '    for (const word of words) {',
  '      if (this.vocab[word]) {',
  '        tokens.push(this.vocab[word]);',
  '      } else {',
  '        // 子词分词',
  '        let remaining = word;',
  '        while (remaining.length > 0) {',
  '          let found = false;',
  '          for (let len = remaining.length; len > 0; len--) {',
  '            const subword = remaining.substring(0, len);',
  '            if (this.vocab[subword]) {',
  '              tokens.push(this.vocab[subword]);',
  '              remaining = remaining.substring(len);',
  '              found = true;',
  '              break;',
  '            }',
  '          }',
  '          if (!found) {',
  '            tokens.push(this.unkToken);',
  '            break;',
  '          }',
  '        }',
  '      }',
  '    }',
  '',
  '    return tokens;',
  '  }',
  '}',
  '',
  'class Optimizer {',
  '  constructor(params, learningRate = 0.001) {',
  '    this.params = params;',
  '    this.learningRate = learningRate;',
  '    this.timestep = 0;',
  '  }',
  '',
  '  step() {',
  '    this.timestep++;',
  '  }',
  '',
  '  zeroGrad() {',
  '    for (const param of this.params) {',
  '      param.grad = new Array(param.grad.length).fill(0);',
  '    }',
  '  }',
  '}',
  '',
  'class AdamOptimizer extends Optimizer {',
  '  constructor(params, learningRate = 0.001, beta1 = 0.9, beta2 = 0.999, epsilon = 1e-8) {',
  '    super(params, learningRate);',
  '    this.beta1 = beta1;',
  '    this.beta2 = beta2;',
  '    this.epsilon = epsilon;',
  '    this.m = params.map(p => new Array(p.length).fill(0));',
  '    this.v = params.map(p => new Array(p.length).fill(0));',
  '  }',
  '',
  '  step() {',
  '    super.step();',
  '    const biasCorrection1 = 1 - Math.pow(this.beta1, this.timestep);',
  '    const biasCorrection2 = 1 - Math.pow(this.beta2, this.timestep);',
  '',
  '    for (let i = 0; i < this.params.length; i++) {',
  '      for (let j = 0; j < this.params[i].length; j++) {',
  '        this.m[i][j] = this.beta1 * this.m[i][j] + (1 - this.beta1) * this.params[i].grad[j];',
  '        this.v[i][j] = this.beta2 * this.v[i][j] + (1 - this.beta2) * Math.pow(this.params[i].grad[j], 2);',
  '',
  '        const mHat = this.m[i][j] / biasCorrection1;',
  '        const vHat = this.v[i][j] / biasCorrection2;',
  '',
  '        this.params[i][j] -= this.learningRate * mHat / (Math.sqrt(vHat) + this.epsilon);',
  '      }',
  '    }',
  '  }',
  '}',
  '',
  'class LossFunction {',
  '  forward(predictions, targets) {',
  '    throw new Error("Not implemented");',
  '  }',
  '',
  '  backward(predictions, targets) {',
  '    throw new Error("Not implemented");',
  '  }',
  '}',
  '',
  'class CrossEntropyLoss extends LossFunction {',
  '  forward(predictions, targets) {',
  '    const losses = [];',
  '    for (let i = 0; i < predictions.length; i++) {',
  '      const pred = predictions[i];',
  '      const target = targets[i];',
  '      const logSumExp = Math.log(pred.reduce((a, b) => a + Math.exp(b), 0));',
  '      losses.push(-pred[target] + logSumExp);',
  '    }',
  '    return losses.reduce((a, b) => a + b, 0) / losses.length;',
  '  }',
  '',
  '  backward(predictions, targets) {',
  '    const grads = [];',
  '    for (let i = 0; i < predictions.length; i++) {',
  '      const pred = predictions[i];',
  '      const target = targets[i];',
  '      const expPred = pred.map(Math.exp);',
  '      const sumExp = expPred.reduce((a, b) => a + b, 0);',
  '      const grad = expPred.map(e => e / sumExp);',
  '      grad[target] -= 1;',
  '      grads.push(grad);',
  '    }',
  '    return grads;',
  '  }',
  '}',
  '',
  '// 初始化MOSS模型',
  'const mossConfig = {',
  '  modelPath: "./models/moss-16b",',
  '  tokenizerPath: "./tokenizers/moss-tokenizer.json",',
  '  hiddenSize: 4096,',
  '  numHeads: 32,',
  '  numLayers: 40,',
  '  intermediateSize: 11008,',
  '  dropoutRate: 0.1,',
  '  maxSequenceLength: 8192,',
  '  vocabSize: 65536,',
  '  useCrossAttention: false',
  '};',
  '',
  'const moss = new MossLLM(mossConfig);',
  'const tokenizer = new Tokenizer(mossConfig.tokenizerPath);',
  'const lossFn = new CrossEntropyLoss();',
  '',
  '// 示例使用',
  'async function runMoss() {',
  '  const prompt = "Explain quantum computing in simple terms.";',
  '  console.log("Input prompt:", prompt);',
  '',
  '  const response = await moss.generate(prompt, {',
  '    maxTokens: 200,',
  '    temperature: 0.8,',
  '    topP: 0.95,',
  '    topK: 50',
  '  });',
  '',
  '  console.log("MOSS Response:", response);',
  '  return response;',
  '}',
  '',
  'async function trainStep(model, batch, optimizer, lossFn) {',
  '  optimizer.zeroGrad();',
  '  const predictions = await model.forward(batch.inputs);',
  '  const loss = lossFn.forward(predictions, batch.targets);',
  '  const grads = lossFn.backward(predictions, batch.targets);',
  '  optimizer.step();',
  '  return loss;',
  '}',
  '',
  'class DataLoader {',
  '  constructor(dataset, batchSize, shuffle = true) {',
  '    this.dataset = dataset;',
  '    this.batchSize = batchSize;',
  '    this.shuffle = shuffle;',
  '    this.indices = Array.from({ length: dataset.length }, (_, i) => i);',
  '    this.currentIndex = 0;',
  '  }',
  '',
  '  reset() {',
  '    this.currentIndex = 0;',
  '    if (this.shuffle) {',
  '      this.indices.sort(() => Math.random() - 0.5);',
  '    }',
  '  }',
  '',
  '  nextBatch() {',
  '    if (this.currentIndex >= this.dataset.length) {',
  '      return null;',
  '    }',
  '',
  '    const batchIndices = this.indices.slice(',
  '      this.currentIndex,',
  '      this.currentIndex + this.batchSize',
  '    );',
  '    this.currentIndex += this.batchSize;',
  '',
  '    const batch = {',
  '      inputs: [],',
  '      targets: []',
  '    };',
  '',
  '    for (const idx of batchIndices) {',
  '      batch.inputs.push(this.dataset[idx].input);',
  '      batch.targets.push(this.dataset[idx].target);',
  '    }',
  '',
  '    return batch;',
  '  }',
  '',
  '  hasNext() {',
  '    return this.currentIndex < this.dataset.length;',
  '  }',
  '}',
  '',
  'async function trainModel(model, trainData, valData, config) {',
  '  const optimizer = new AdamOptimizer(model.parameters(), config.learningRate);',
  '  const lossFn = new CrossEntropyLoss();',
  '  const trainLoader = new DataLoader(trainData, config.batchSize);',
  '  const valLoader = new DataLoader(valData, config.batchSize, false);',
  '',
  '  for (let epoch = 0; epoch < config.numEpochs; epoch++) {',
  '    console.log(`Epoch ${epoch + 1}/${config.numEpochs}`);',
  '    trainLoader.reset();',
  '    let totalTrainLoss = 0;',
  '    let numTrainBatches = 0;',
  '',
  '    while (trainLoader.hasNext()) {',
  '      const batch = trainLoader.nextBatch();',
  '      const loss = await trainStep(model, batch, optimizer, lossFn);',
  '      totalTrainLoss += loss;',
  '      numTrainBatches++;',
  '    }',
  '',
  '    const avgTrainLoss = totalTrainLoss / numTrainBatches;',
  '    console.log(`  Train Loss: ${avgTrainLoss.toFixed(4)}`);',
  '',
  '    valLoader.reset();',
  '    let totalValLoss = 0;',
  '    let numValBatches = 0;',
  '',
  '    while (valLoader.hasNext()) {',
  '      const batch = valLoader.nextBatch();',
  '      const predictions = await model.forward(batch.inputs);',
  '      const loss = lossFn.forward(predictions, batch.targets);',
  '      totalValLoss += loss;',
  '      numValBatches++;',
  '    }',
  '',
  '    const avgValLoss = totalValLoss / numValBatches;',
  '    console.log(`  Val Loss: ${avgValLoss.toFixed(4)}`);',
  '  }',
  '}',
  '',
  'class CheckpointManager {',
  '  constructor(checkpointDir, maxCheckpoints = 5) {',
  '    this.checkpointDir = checkpointDir;',
  '    this.maxCheckpoints = maxCheckpoints;',
  '    this.checkpoints = [];',
  '  }',
  '',
  '  save(model, optimizer, epoch, loss) {',
  '    const checkpoint = {',
  '      modelState: model.getState(),',
  '      optimizerState: optimizer.getState(),',
  '      epoch: epoch,',
  '      loss: loss,',
  '      timestamp: Date.now()',
  '    };',
  '',
  '    const filename = `checkpoint_epoch_${epoch}.pt`;',
  '    this.checkpoints.push({ filename, timestamp: checkpoint.timestamp });',
  '',
  '    if (this.checkpoints.length > this.maxCheckpoints) {',
  '      const oldest = this.checkpoints.shift();',
  '      this.deleteCheckpoint(oldest.filename);',
  '    }',
  '',
  '    return filename;',
  '  }',
  '',
  '  load(filename) {',
  '    const checkpoint = this.readCheckpoint(filename);',
  '    return checkpoint;',
  '  }',
  '',
  '  getLatest() {',
  '    if (this.checkpoints.length === 0) return null;',
  '    return this.checkpoints[this.checkpoints.length - 1];',
  '  }',
  '',
  '  deleteCheckpoint(filename) {',
  '    // 删除旧检查点',
  '  }',
  '',
  '  readCheckpoint(filename) {',
  '    // 读取检查点文件',
  '    return null;',
  '  }',
  '}',
  '',
  '// 系统初始化',
  'console.log("Initializing MOSS artificial intelligence system...");',
  'console.log("Loading tokenizer...");',
  'console.log("Loading model weights...");',
  'console.log("Configuring optimization pipeline...");',
  'console.log("System ready.");'
];

export const CodeRain: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [currentLine, setCurrentLine] = useState(0);
  const [displayedLines, setDisplayedLines] = useState<string[]>([]);
  const [showCursor, setShowCursor] = useState(true);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // 设置canvas尺寸
    const resizeCanvas = () => {
      canvas.width = window.innerWidth * 0.5; // 左侧50%宽度，铺满左侧
      canvas.height = window.innerHeight;
      // 重新初始化矩阵状态
      initMatrixState();
    };
    resizeCanvas();
    window.addEventListener('resize', resizeCanvas);

    // 加载代码行
    const loadCodeLine = () => {
      if (currentLine < mossCodeSnippets.length) {
        setDisplayedLines(prev => {
          // 计算当前显示的行数是否超过画布高度
          const fontSize = 14;
          const lineHeight = fontSize + 4;
          const maxLines = Math.floor((canvas.height - 40) / lineHeight);
          
          // 如果超过最大行数，移除最上面的一行
          if (prev.length >= maxLines) {
            return [...prev.slice(1), mossCodeSnippets[currentLine]];
          }
          return [...prev, mossCodeSnippets[currentLine]];
        });
        setCurrentLine(prev => prev + 1);
      }
    };

    // 每150毫秒加载代码行，逐行出现
    const lineInterval = setInterval(loadCodeLine, 150);

    // 光标闪烁效果
    const cursorInterval = setInterval(() => {
      setShowCursor(prev => !prev);
    }, 500);

    // 存储矩阵背景的状态，避免每次重绘
    const matrixState = {
      chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?/\\~`'.split(''),
      drops: [],
      fontSize: 14
    };

    // 初始化矩阵状态
    const initMatrixState = () => {
      const columns = Math.floor(canvas.width / matrixState.fontSize);
      matrixState.drops = Array(columns).fill(1).map(() => Math.floor(Math.random() * canvas.height / matrixState.fontSize));
    };
    initMatrixState();

    const draw = () => {
      // 使用不透明背景，避免累积效果
      ctx.fillStyle = 'rgba(10, 14, 23, 1)';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // 设置字体和颜色
      const fontSize = 14;
      ctx.font = `${fontSize}px Consolas, Monaco, monospace`;

      // 绘制已加载的代码行
      displayedLines.forEach((line, index) => {
        // 计算位置
        const x = 20;
        const y = 40 + index * (fontSize + 4);

        // 创建渐变色
        const gradient = ctx.createLinearGradient(x, y - fontSize * 5, x, y);
        gradient.addColorStop(0, 'rgba(100, 255, 218, 0)');
        gradient.addColorStop(0.5, 'rgba(100, 255, 218, 0.7)');
        gradient.addColorStop(1, 'rgba(100, 255, 218, 1)');

        ctx.fillStyle = gradient;
        ctx.fillText(line, x, y);
      });

      // 绘制光标
      if (showCursor && displayedLines.length > 0) {
        const lastLine = displayedLines[displayedLines.length - 1];
        const fontSize = 14;
        const x = 20 + ctx.measureText(lastLine).width;
        const y = 40 + (displayedLines.length - 1) * (fontSize + 4);
        
        ctx.fillStyle = 'rgba(100, 255, 218, 1)';
        ctx.fillRect(x, y - fontSize + 2, 2, fontSize - 2);
      }

      // 绘制矩阵风格的背景字符
      const columns = Math.floor(canvas.width / matrixState.fontSize);
      
      // 确保drops数组长度正确
      if (matrixState.drops.length !== columns) {
        initMatrixState();
      }

      for (let i = 0; i < matrixState.drops.length; i++) {
        // 随机选择字符
        const char = matrixState.chars[Math.floor(Math.random() * matrixState.chars.length)];

        // 计算位置
        const x = i * matrixState.fontSize;
        const y = matrixState.drops[i] * matrixState.fontSize;

        // 淡色背景字符
        ctx.fillStyle = 'rgba(100, 255, 218, 0.1)';
        ctx.fillText(char, x, y);

        // 随机重置或继续下落
        if (matrixState.drops[i] * matrixState.fontSize > canvas.height && Math.random() > 0.975) {
          matrixState.drops[i] = 0;
        }

        matrixState.drops[i]++;
      }
    };

    const drawInterval = setInterval(draw, 50);

    return () => {
      clearInterval(drawInterval);
      clearInterval(lineInterval);
      clearInterval(cursorInterval);
      window.removeEventListener('resize', resizeCanvas);
    };
  }, [currentLine, displayedLines, showCursor]);

  return (
    <canvas
      ref={canvasRef}
      className="absolute left-0 top-0 h-full z-0"
      style={{ width: '50%', opacity: 0.9 }}
    />
  );
};
